apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: winhd1
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 150Gi
---
apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  name: win10-tesla-m6
spec:
  running: false
  template:
    metadata:
      labels:
        kubevirt.io/domain: win10-tesla-m6
    spec:
      domain:
        cpu:
          cores: 6
        devices:
          gpus:
          - deviceName: "nvidia.com/GM204GL_TESLA_M6"
            name: gpu1
          disks:
          - bootOrder: 1
            cdrom:
              bus: sata
            name: cdromiso
          - bootOrder: 2
            disk:
              bus: virtio
            name: harddrive
          - bootOrder: 3
            cdrom:
              bus: sata
            name: virtiocontainerdisk
        machine:
          type: q35
        resources:
          requests:
            memory: 12G
      volumes:
      - name: cdromiso
        persistentVolumeClaim:
          claimName: iso-win10
      - name: harddrive
        persistentVolumeClaim:
          claimName: winhd1
      - containerDisk:
          image: quay.io/kubevirt/virtio-container-disk
        name: virtiocontainerdisk
