apiVersion: snapshot.kubevirt.io/v1alpha1
kind: VirtualMachineRestore
metadata:
  name: restore-win10-tesla-m6
spec:
  target:
    apiGroup: kubevirt.io
    kind: VirtualMachine
    name: win10-tesla-m6
  virtualMachineSnapshotName: snap-win10-tesla-m6
