kind: VirtualMachineClone
apiVersion: "clone.kubevirt.io/v1alpha1"
metadata:
  name: testclone

spec:
  # source & target definitions
  source:
    apiGroup: kubevirt.io
    kind: VirtualMachine
    name: win10-tesla-m6
  target:
    apiGroup: kubevirt.io
    kind: VirtualMachine
    name: vm-clone-target

