---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: winhd1-clone
spec:
  storageClassName: rook-ceph-block
  dataSource:
    name: winhd1
    kind: PersistentVolumeClaim
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 150Gi
