apiVersion: v1
kind: Pod
metadata:
  name: jear-cuda-vectoradd3-m6
spec:
  restartPolicy: OnFailure
  containers:
  - name: vectoradd
    image: nvidia/samples:vectoradd-cuda11.2.1
    resources:
      limits:
        nvidia.com/gpu: 1
  nodeSelector:
    nvidia.com/gpu.product: Tesla-M6
