apiVersion: cdi.kubevirt.io/v1beta1
kind: DataVolume
metadata:
  name: "datavolume-from-pvc"
spec:
  source:
    pvc:
      namespace: "default"
      name: "restore-6cd52cea-a4fd-496b-b96c-9c03caac7423-harddrive"
  pvc:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: "150Gi"
