apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: restore-ee890b70-bad4-46d2-9bf5-8064582e9101-harddrive
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 150Gi
---
apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  name: win10pro-01
spec:
  running: false
  template:
    metadata:
      labels:
        kubevirt.io/domain: win10pro
    spec:
      domain:
        cpu:
          cores: 6
        devices:
          disks:
          - bootOrder: 1
            disk:
              bus: virtio
            name: harddrive
        machine:
          type: q35
        resources:
          requests:
            memory: 12G
      volumes:
      - name: harddrive
        persistentVolumeClaim:
          claimName: restore-ee890b70-bad4-46d2-9bf5-8064582e9101-harddrive
