apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: restore-bfb35f4f-153e-44d1-bceb-22689bd04470-harddrive
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 150Gi
---
apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  name: win10pro-02
spec:
  running: false
  template:
    metadata:
      labels:
        kubevirt.io/domain: win10pro-02
    spec:
      domain:
        cpu:
          cores: 6
        devices:
          disks:
          - bootOrder: 1
            disk:
              bus: virtio
            name: harddrive
        machine:
          type: q35
        resources:
          requests:
            memory: 12G
      volumes:
      - name: harddrive
        persistentVolumeClaim:
          claimName: restore-bfb35f4f-153e-44d1-bceb-22689bd04470-harddrive
