---
apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  name: win10-tesla-m6
spec:
  running: false
  template:
    metadata:
      labels:
        kubevirt.io/domain: win10-tesla-m6
    spec:
      domain:
        cpu:
          cores: 6
        devices:
          gpus:
          - deviceName: "nvidia.com/GM204GL_TESLA_M6"
            name: gpu1
        machine:
          type: q35
        resources:
          requests:
            memory: 12G
